spring.application.name=car-producer
grpc.client.car-consumer.address=static://localhost:9090
grpc.client.car-consumer.negotiation-type=plaintext
server.port=8081
spring.main.web-application-type=none