spring.application.name=car-producer
grpc.client.car-consumer.address=static://localhost:9090
grpc.client.car-consumer.negotiation-type=plaintext
server.port=8081
spring.main.web-application-type=none
# Kafka general
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
# Kafka topics
kafka.topic.positions=car-positions
kafka.topic.diagnostics=car-diagnostics
kafka.consumer.group-id=car-telemetry-group

# Generator
generator.vehicle.count=10
generator.stop.probability=2
generator.stop.min.seconds=300
generator.stop.max.seconds=300
generator.position.delta=0.00015
generator.heading.change.degrees=20