spring.application.name=car-consumer
grpc.server.port=9090
spring.data.mongodb.uri=mongodb://localhost:27017/cartelemetry
analytics.schedule.rate=600000
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=car-telemetry-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.auto-offset-reset=earliest